-- Mantener la credencial existente y su titular; retirar solo la fila vacía inicial.
DELETE FROM google_calendar_connection WHERE owner_dpi IS NULL AND encrypted_refresh_token IS NULL;
DO $$ DECLARE constraint_name text;
BEGIN
    FOR constraint_name IN
        SELECT conname FROM pg_constraint
        WHERE conrelid='google_calendar_connection'::regclass AND contype='c'
          AND pg_get_constraintdef(oid) LIKE '%id = 1%'
    LOOP
        EXECUTE format('ALTER TABLE google_calendar_connection DROP CONSTRAINT %I', constraint_name);
    END LOOP;
END $$;
ALTER TABLE google_calendar_connection ALTER COLUMN id TYPE bigint;
ALTER TABLE google_calendar_connection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('google_calendar_connection','id'),
              greatest(coalesce((SELECT max(id) FROM google_calendar_connection),0),1),true);
ALTER TABLE google_calendar_connection ALTER COLUMN owner_dpi SET NOT NULL;
ALTER TABLE google_calendar_connection ADD CONSTRAINT agenda_connection_owner UNIQUE(owner_dpi);
CREATE UNIQUE INDEX agenda_connected_google_account ON google_calendar_connection(google_subject) WHERE google_subject IS NOT NULL AND state<>'DISCONNECTED';
ALTER TABLE agenda_sync_outbox ADD COLUMN connection_id bigint REFERENCES google_calendar_connection(id);
UPDATE agenda_sync_outbox SET connection_id=(SELECT id FROM google_calendar_connection ORDER BY id LIMIT 1)
WHERE completed_at IS NULL;
ALTER TABLE legal_process_calendar
    ADD COLUMN recurrence_frequency varchar(10),
    ADD COLUMN recurrence_until date,
    ADD COLUMN master_revision bigint NOT NULL DEFAULT 0,
    ADD CONSTRAINT agenda_recurrence CHECK (
        (recurrence_frequency IS NULL AND recurrence_until IS NULL) OR
        (recurrence_frequency IN ('DAILY','WEEKLY','MONTHLY','YEARLY') AND recurrence_until IS NOT NULL));
-- Conservar la revisión de eventos ya publicados: la siguiente edición debe volver a enviarse.
UPDATE legal_process_calendar SET master_revision=version;
ALTER TABLE agenda_google_event ADD COLUMN synced_master_revision bigint NOT NULL DEFAULT -1;
UPDATE agenda_google_event SET synced_master_revision=synced_version WHERE state='SYNCED';
ALTER TABLE agenda_event_history ADD COLUMN original_starts_at timestamptz;
CREATE TABLE agenda_event_exception (
    event_id bigint NOT NULL REFERENCES legal_process_calendar(id),
    original_starts_at timestamptz NOT NULL,
    starts_at timestamptz NOT NULL,
    ends_at timestamptz NOT NULL,
    title varchar(150) NOT NULL,
    description varchar(2000),
    location varchar(255),
    status varchar(20) NOT NULL CHECK(status IN ('SCHEDULED','COMPLETED','CANCELLED')),
    revision bigint NOT NULL,
    google_event_id varchar(1024),
    etag varchar(255),
    synced_revision bigint NOT NULL DEFAULT -1,
    PRIMARY KEY(event_id,original_starts_at),
    CHECK(ends_at>starts_at AND ends_at<=starts_at+interval '31 days')
);
CREATE TABLE agenda_google_audit (
    id bigserial PRIMARY KEY,
    operator_dpi varchar(15) NOT NULL REFERENCES user_system(dpi),
    calendar_id varchar(255) NOT NULL,
    google_event_id varchar(1024) NOT NULL,
    action varchar(30) NOT NULL,
    recorded_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX agenda_exception_window ON agenda_event_exception(starts_at,ends_at);
CREATE INDEX agenda_jobs_connection ON agenda_sync_outbox(connection_id) WHERE completed_at IS NULL;
